# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2216182a4fd7db13361d34cc5a2cdeb7a3eb5d2309f1f147bf442ed7711032fda21c470a0a453db93849521a62934a4bc47dd3cb170182060c5fa2c3c414044b

test:
  secret_key_base: d57912d04e87c8a94765f148d6edb08dc85605d24d14bc55c127a731c0cd30eeee5831461a1aa68eee3e6d5c640866fdb5c10398b94083b45f3bdff58ddb6a77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
